const categoriesNormal = [
  "Name 3 Pizza Toppings",
  "Name 3 Marvel Movies",
  "Name 3 Things You Find in a Glovebox",
  "Name 3 Breeds of Dog",
  "Name 3 Social Media Apps",
  "Name 3 Things That are Red",
  "Name 3 Ivy League Universities",
  "Name 3 Card Games",
  "Name 3 Things You Do Before Bed",
  "Name 3 Continents",
  "Name 3 Planets",
  "Name 3 Harry Potter Characters",
  "Name 3 Fast Food Chains",
  "Name 3 Things You Eat with a Spoon",
  "Name 3 Taylor Swift Songs",
  "Name 3 Things That Smell Good",
  "Name 3 Colors in a Rainbow",
  "Name 3 US Presidents",
  "Name 3 Things You Find in a Bathroom",
  "Name 3 Breakfast Foods",
  "Name 3 Streaming Services",
  "Name 3 Sports Played with a Ball",
  "Name 3 Luxury Car Brands",
  "Name 3 Things in Your Pocket Right Now",
  "Name 3 Video Games",
  "Name 3 Types of Pasta",
  "Name 3 Musical Instruments",
  "Name 3 Reality TV Shows",
  "Name 3 Things You Can't Buy with Money",
  "Name 3 Things That Are Sticky",
  "Name 3 Animals That Lay Eggs",
  "Name 3 Things You Find at a Beach",
  "Name 3 Soft Drinks",
  "Name 3 Characters from The Office",
  "Name 3 Things You Plug In",
  "Name 3 Holidays",
  "Name 3 Ice Cream Flavors",
  "Name 3 Superheroes",
  "Name 3 Things That Make You Sneeze",
  "Name 3 European Countries",
  "Name 3 Languages",
  "Name 3 Types of Cheese",
  "Name 3 Board Games",
  "Name 3 Things You Wear on Your Feet",
  "Name 3 Types of Flower",
  "Name 3 Things in a Toolkit",
  "Name 3 Pixar Movies",
  "Name 3 Fruits That Are Green",
  "Name 3 Things That Are Cold",
  "Name 3 Brands of Sneaker",
  "Name 3 Things You Do at a Wedding",
  "Name 3 Capital Cities",
  "Name 3 Ocean Animals",
  "Name 3 Things With Wheels",
  "Name 3 Desserts",
  "Name 3 Things You Cut with Scissors",
  "Name 3 Jobs That Require a Uniform",
  "Name 3 Things Made of Glass",
  "Name 3 Words That Start with 'Z'",
  "Name 3 Things You Find in a Fridge",
  "Name 3 Types of Weather",
  "Name 3 Things You Can Rent",
  "Name 3 Things You Lose Often",
  "Name 3 Animals in the Jungle",
  "Name 3 Internet Browsers",
  "Name 3 Things You Do in the Morning",
  "Name 3 Types of Sandwich",
  "Name 3 Things You Need for Camping",
  "Name 3 Coffee Drinks",
  "Name 3 Things That Fly",
  "Name 3 Rooms in a House",
  "Name 3 Things You Buy by the Dozen",
  "Name 3 Cartoons",
  "Name 3 Things You Find in a Gym",
  "Name 3 Types of Shoe",
  "Name 3 Things You Lick",
  "Name 3 Vegetables You Hate",
  "Name 3 Things You Keep in a Wallet",
  "Name 3 Famous Painters",
  "Name 3 Things That Are Noisy",
  "Name 3 Zoo Animals",
  "Name 3 Things You Do on Your Birthday",
  "Name 3 Things Made of Wood",
  "Name 3 Toothpaste Brands",
  "Name 3 Things You Drink from a Mug",
  "Name 3 Gym Exercises",
  "Name 3 Things You Find in a School Bag",
  "Name 3 Types of Cereal",
  "Name 3 Things That Are Round",
  "Name 3 Famous Michaels",
  "Name 3 Things You Find Under a Bed",
  "Name 3 Condiments",
  "Name 3 Birds",
  "Name 3 Kardashian/Jenners",
  "Name 3 Things With Buttons",
  "Name 3 Salad Dressings",
  "Name 3 Things You Put on a Burger",
  "Name 3 Excuses for Being Late",
  "Name 3 Things You Should Not Say on a First Date",
  "Name 3 Programming Languages",
  "Name 3 Things You Can Grill",
  "Name 3 Bad Habits",
  "Name 3 Things That Rhyme with 'Cat'",
  "Name 3 Types of Shark",
  "Name 3 Things You Do When You're Sick",
  "Name 3 Places You Need a Ticket to Enter",
  "Name 3 Fairy Tales",
  "Name 3 Things That Have a Screen",
  "Name 3 Types of Tea",
  "Name 3 Things You Can Fold",
  "Name 3 Kitchen Appliances",
  "Name 3 Star Wars Characters",
  "Name 3 Things You Do in Snow",
  "Name 3 Types of Hat",
  "Name 3 Red Fruits",
  "Name 3 Things Found in a Library",
  "Name 3 Disney Princesses",
  "Name 3 Things That Float",
  "Name 3 Muscles in the Human Body",
];

const categoriesHard = [
  "Name 5 US States",
  "Name 5 Colors in a Box of Crayons",
  "Name 5 Body Parts",
  "Name 5 Things You Find in a Kitchen",
  "Name 5 Boys Names Starting with 'J'",
  "Name 5 Girls Names Starting with 'S'",
  "Name 5 Movies Starring Tom Cruise",
  "Name 5 Things That Are Blue",
  "Name 5 Farm Animals",
  "Name 5 Months of the Year",
  "Name 5 Disney Princesses",
  "Name 5 Things You Pack in a Suitcase",
  "Name 5 Types of Fruit",
  "Name 5 Things You See at a Zoo",
  "Name 5 Candy Bars",
  "Name 5 Apps on Your Phone Home Screen",
  "Name 5 Things Made of Plastic",
  "Name 5 Sports Teams (Any Sport)",
  "Name 5 Things You Do at School",
  "Name 5 Things That Smell Bad",
  "Name 5 Clothing Brands",
  "Name 5 Things in a Toolbox",
  "Name 5 Vegetables",
  "Name 5 Shapes",
  "Name 5 Things with a Screen",
  "Name 5 Rappers",
  "Name 5 Things You Find in a Park",
  "Name 5 Capital Cities in Europe",
  "Name 5 Things You Buy at a Gas Station",
  "Name 5 Types of Drink (Alcoholic or Non)",
  "Name 5 Harry Potter Spells",
  "Name 5 Things That Are Sharp",
  "Name 5 Musical Genres",
  "Name 5 Things You Can Recycle",
  "Name 5 Things That Burn",
  "Name 5 Careers/Jobs",
  "Name 5 Insects",
  "Name 5 Things You Do on a Plane",
  "Name 5 Video Game Consoles (Past or Present)",
  "Name 5 Things Made of Metal",
  "Name 5 Top 40 Pop Singers",
  "Name 5 Things You Find in a Movie Theater",
  "Name 5 Car Parts",
  "Name 5 Makeup Products",
  "Name 5 Things You Find in a Hospital",
  "Name 5 Rhymes for the Word 'Cat'",
  "Name 5 Things You Do When You Wake Up",
  "Name 5 Types of Tree",
  "Name 5 Mammals",
  "Name 5 Things That Are Yellow",
  "Name 5 Things You Use in the Shower",
  "Name 5 Pizza Chains",
  "Name 5 Things That Use Batteries",
  "Name 5 Planets or Moons",
  "Name 5 Card Games",
  "Name 5 Things Found in a Desk Drawer",
  "Name 5 Popular Last Names",
  "Name 5 Things You Wear in Winter",
  "Name 5 Birds That Can Fly",
  "Name 5 Things You Find in a Garage",
  "Name 5 Streaming TV Shows",
  "Name 5 Things That Are Heavy",
  "Name 5 Words That Start with 'A'",
  "Name 5 Asian Countries",
  "Name 5 Things You Can Grill",
  "Name 5 Bank Holidays",
  "Name 5 Things You Find in a Purse",
  "Name 5 Animals That Can Swim",
  "Name 5 Computer Parts",
  "Name 5 Famous Athletes",
  "Name 5 Things You Shout",
  "Name 5 Types of Soup",
  "Name 5 Furniture Items",
  "Name 5 Things Made of Paper",
  "Name 5 Things That Are Sweet",
  "Name 5 Things You Find at a Carnival",
  "Name 5 Science Fiction Movies",
  "Name 5 Things That Grow Underground",
  "Name 5 Synonyms for 'Happy'",
  "Name 5 Olympic Sports",
  "Name 5 Things You Do With Your Hands",
  "Name 5 Modes of Transportation",
  "Name 5 Things You Find in a Library",
  "Name 5 Types of Cake",
  "Name 5 Things That Are Soft",
  "Name 5 Beer Brands",
  "Name 5 Action Movies",
  "Name 5 Things You Don't Want to Touch",
  "Name 5 Currencies (Money types)",
  "Name 5 Things Found in an Office",
  "Name 5 Words That Rhyme with 'Go'",
  "Name 5 Things You Can Juggle",
  "Name 5 Flavors of Chips",
  "Name 5 Things You Find in a Church",
  "Name 5 Wireless Devices",
  "Name 5 Things That Are Expensive",
  "Name 5 Fish",
  "Name 5 Things You Find in a Hotel Room",
  "Name 5 Reasons to Call 911"
];

export {categoriesNormal, categoriesHard}