export const categories = {
	normal: [
		'Name 3 pizza toppings',
		'Name 3 dog breeds',
		'Name 3 ice cream flavors',
		'Name 3 breakfast cereals',
		'Name 3 fast food chains',
		'Name 3 super heroes',
		'Name 3 types of fruit',
		'Name 3 vegetables',
		'Name 3 zoo animals',
		'Name 3 types of candy',
		'Name 3 board games',
		'Name 3 card games',
		'Name 3 sports teams',
		'Name 3 car brands',
		'Name 3 shoe brands',
		'Name 3 soda brands',
		'Name 3 items in a fridge',
		'Name 3 items in a bathroom',
		'Name 3 items in a garage',
		'Name 3 items in a school bag',
		'Name 3 school subjects',
		'Name 3 planets',
		'Name 3 colors in a rainbow',
		'Name 3 farm animals',
		'Name 3 ocean animals',
		'Name 3 bird species',
		'Name 3 types of pasta',
		'Name 3 pizza places',
		'Name 3 coffee shops',
		'Name 3 things that are yellow',
		'Name 3 things that are red',
		'Name 3 things that are blue',
		'Name 3 things that are green',
		'Name 3 things that are black',
		'Name 3 musical instruments',
		'Name 3 shapes',
		'Name 3 countries in Europe',
		'Name 3 countries in Asia',
		'Name 3 US states',
		'Name 3 cities in the world',
		'Name 3 items on a desk',
		'Name 3 things in a wallet',
		'Name 3 things in a purse',
		'Name 3 clothing items',
		'Name 3 winter accessories',
		'Name 3 types of shoes',
		'Name 3 holiday destinations',
		'Name 3 theme parks',
		'Name 3 cartoon characters',
		'Name 3 movie genres',
		'Name 3 types of music',
		'Name 3 instruments in a band',
		'Name 3 things you do in the morning',
		'Name 3 things you do before bed',
		'Name 3 things you do at the beach',
		'Name 3 things you find in a park',
		'Name 3 types of trees',
		'Name 3 garden flowers',
		'Name 3 kitchen appliances',
		'Name 3 baking ingredients',
		'Name 3 spices in a cabinet',
		'Name 3 types of soup',
		'Name 3 sandwich fillings',
		'Name 3 ways to cook an egg',
		'Name 3 ways to eat a potato',
		'Name 3 snacks for a movie',
		'Name 3 junk foods',
		'Name 3 healthy foods',
		'Name 3 green vegetables',
		'Name 3 citrus fruits',
		'Name 3 berries',
		'Name 3 things you find under a bed',
		'Name 3 things you find in a junk drawer',
		'Name 3 things you find in a closet',
		'Name 3 things you find in a toolbox',
		'Name 3 tools',
		'Name 3 stationery items',
		'Name 3 types of pens',
		'Name 3 things you write with',
		'Name 3 things you read',
		'Name 3 famous authors',
		'Name 3 famous painters',
		'Name 3 olympic sports',
		'Name 3 ball games',
		'Name 3 hobbies',
		'Name 3 weekend activities',
		'Name 3 ways to travel',
		'Name 3 types of boats',
		'Name 3 types of planes',
		'Name 3 emergency services',
		'Name 3 professions',
		'Name 3 jobs that wear uniforms',
		'Name 3 jobs that work outdoors',
		'Name 3 tech companies',
		'Name 3 video games',
		'Name 3 phone apps',
		'Name 3 social media sites',
		'Name 3 things you plug in',
		'Name 3 things that use batteries',
		'Name 3 remote controls',
		'Name 3 things with buttons',
		'Name 3 things that make noise',
		'Name 3 things that smell good',
		'Name 3 things that smell bad',
		'Name 3 things that are soft',
		'Name 3 things that are hard',
		'Name 3 things that are sharp',
		'Name 3 things that are heavy',
		'Name 3 things that are light',
		'Name 3 things that are sticky',
		'Name 3 things that are cold',
		'Name 3 things that are hot',
		'Name 3 things that are sweet',
		'Name 3 things that are sour',
		'Name 3 things that are spicy',
		'Name 3 types of nuts',
		'Name 3 things you put on toast',
		'Name 3 things you put in tea',
		'Name 3 things you put in coffee',
		'Name 3 things you put in a salad',
		'Name 3 things you put in a burger',
		'Name 3 breakfast items',
		'Name 3 things you find at a wedding',
		'Name 3 things you find at a birthday party',
		'Name 3 things you find at a circus',
		'Name 3 things you find at a zoo',
		'Name 3 things you find in a hospital',
		'Name 3 things you find in a library',
		'Name 3 things you find in a museum',
		'Name 3 things you find in a gym',
		'Name 3 things you find in a hotel room',
		'Name 3 items of furniture',
		'Name 3 types of chairs',
		'Name 3 types of tables',
		'Name 3 things you sit on',
		'Name 3 things you sleep on',
		'Name 3 things you wear on your head',
		'Name 3 things you wear on your hands',
		'Name 3 things you wear on your feet',
		'Name 3 types of jewelry',
		'Name 3 makeup items',
		'Name 3 hair products',
		'Name 3 cleaning supplies',
		'Name 3 chores around the house',
		'Name 3 things you do in the garden',
		'Name 3 ways to say hello',
		'Name 3 ways to say goodbye',
		'Name 3 languages',
		'Name 3 body parts',
		'Name 3 internal organs',
		'Name 3 things with wheels',
		'Name 3 things with wings',
		'Name 3 things with tails',
		'Name 3 things with four legs',
		'Name 3 things that swim',
		'Name 3 things that fly',
		'Name 3 things that crawl',
		'Name 3 things that jump',
		'Name 3 things that grow in the ground',
		'Name 3 things that grow on trees',
		'Name 3 things that are frozen',
		'Name 3 things that melt',
		'Name 3 things that burn',
		'Name 3 things that float',
		'Name 3 things that sink',
		'Name 3 things that break easily',
		'Name 3 things that last forever',
		'Name 3 things that are expensive',
		'Name 3 things that are free',
		'Name 3 things that are cheap',
		'Name 3 things that are shiny',
		'Name 3 things that are transparent',
		'Name 3 things that are metal',
		'Name 3 things that are wood',
		'Name 3 things that are plastic',
		'Name 3 things that are paper',
		'Name 3 things that are glass',
		'Name 3 things that are round',
		'Name 3 things that are square',
		'Name 3 things that are triangular',
		'Name 3 things you open',
		'Name 3 things you close',
		'Name 3 things you push',
		'Name 3 things you pull',
		'Name 3 things you turn on',
		'Name 3 things you turn off',
		'Name 3 things you clean with',
		'Name 3 things you fix with',
		'Name 3 things you cook with',
		'Name 3 things you eat with',
		'Name 3 things you drink from',
		'Name 3 things you cut with',
		'Name 3 things you tie',
		'Name 3 things you fold',
		'Name 3 things you stack',
		'Name 3 things you throw',
		'Name 3 things you catch',
		'Name 3 things you kick',
		'Name 3 things you carry',
	],
	normalMature: [
		'Name 3 pickup lines',
		'Name 3 reasons to ghost someone',
		'Name 3 types of alcohol',
		'Name 3 cocktail names',
		'Name 3 brands of beer',
		'Name 3 brands of vodka',
		'Name 3 brands of condoms',
		'Name 3 places to have a first date',
		'Name 3 reasons for a breakup',
		'Name 3 dating apps',
		'Name 3 types of wine',
		'Name 3 things to do while drunk',
		'Name 3 hangover cures',
		"Name 3 things you shouldn't say on a date",
		'Name 3 places to hide a body',
		'Name 3 excuses for being late to work',
		'Name 3 ways to get fired',
		'Name 3 things you do in the shower',
		'Name 3 things people lie about',
		'Name 3 reasons to block someone',
		'Name 3 red flags in a partner',
		'Name 3 green flags in a partner',
		'Name 3 things found in a bedroom',
		'Name 3 things you do in the dark',
		'Name 3 things you find at a bachelor party',
		'Name 3 things you find at a bachelorette party',
		'Name 3 stripper names',
		'Name 3 places people get tattoos',
		'Name 3 places people get piercings',
		'Name 3 things that make you blush',
		'Name 3 things that make you cringe',
		'Name 3 ways to cheat on a test',
		'Name 3 ways to cheat on a diet',
		'Name 3 guilty pleasures',
		'Name 3 bad habits',
		'Name 3 things you do when you are home alone',
		"Name 3 things you shouldn't do at a funeral",
		"Name 3 things you shouldn't do at a wedding",
		"Name 3 things you shouldn't do in an elevator",
		"Name 3 things you shouldn't do in a library",
		"Name 3 things you shouldn't do in a movie theater",
		'Name 3 dirty words',
		'Name 3 swear words',
		'Name 3 insults',
		'Name 3 compliments',
		'Name 3 things you find in a nightclub',
		'Name 3 things you find in a bar',
		'Name 3 things you find in a casino',
		'Name 3 games you play at a party',
		'Name 3 drinking games',
		'Name 3 types of shots',
		'Name 3 things you do in a bathroom stall',
		'Name 3 things you find in a medicine cabinet',
		'Name 3 things you find in a bedside table',
		'Name 3 things you hide from your parents',
		'Name 3 things you hide from your boss',
		'Name 3 things you hide from your partner',
		'Name 3 reasons to see a therapist',
		'Name 3 reasons to call the police',
		'Name 3 reasons to go to the ER',
		'Name 3 things you do on a Friday night',
		'Name 3 things you do on a Sunday morning',
		"Name 3 things you do when you're bored",
		"Name 3 things you do when you're angry",
		"Name 3 things you do when you're sad",
		"Name 3 things you do when you're happy",
		'Name 3 things that make you nervous',
		'Name 3 things that make you excited',
		'Name 3 things that make you angry',
		'Name 3 things that make you scared',
		'Name 3 phobias',
		'Name 3 fetishes',
		'Name 3 taboos',
		'Name 3 conspiracy theories',
		'Name 3 urban legends',
		'Name 3 scary movies',
		'Name 3 horror movie villains',
		'Name 3 things you find in a haunted house',
		'Name 3 things you find in a dungeon',
		'Name 3 things you find in a basement',
		'Name 3 things you find in an attic',
		'Name 3 things you find in a dumpster',
		'Name 3 things you find in an alleyway',
		'Name 3 things you find in a dark forest',
		'Name 3 things you find in a graveyard',
		'Name 3 things you find at a crime scene',
		'Name 3 weapons',
		'Name 3 ways to die',
		'Name 3 ways to kill a spider',
		'Name 3 ways to annoy a neighbor',
		'Name 3 ways to annoy a coworker',
		'Name 3 ways to annoy a sibling',
		'Name 3 ways to annoy a parent',
		'Name 3 ways to annoy a teacher',
		'Name 3 ways to spend a million dollars',
		'Name 3 ways to lose a million dollars',
		'Name 3 ways to get rich quick',
		'Name 3 ways to get famous',
		'Name 3 ways to get noticed',
		'Name 3 ways to get revenge',
		'Name 3 ways to get a date',
		'Name 3 ways to get out of a date',
		'Name 3 ways to get out of a ticket',
		'Name 3 ways to get out of school',
		'Name 3 ways to get out of work',
		'Name 3 ways to get out of a conversation',
		'Name 3 ways to get out of a social event',
		'Name 3 things you do at a strip club',
		'Name 3 things you do at a music festival',
		'Name 3 things you do at a rave',
		'Name 3 things you do at a tailgate',
		'Name 3 things you do at a house party',
		'Name 3 things you do at a dive bar',
		'Name 3 things you do at a fancy restaurant',
		'Name 3 things you do at a fast food place',
		'Name 3 things you do at a gas station',
		'Name 3 things you do at a convenience store',
		'Name 3 things you do at a mall',
		'Name 3 things you do at a park',
		'Name 3 things you do at a beach',
		'Name 3 things you do at a pool',
		'Name 3 things you do at a gym',
		'Name 3 things you do at a spa',
		'Name 3 things you do at a salon',
		'Name 3 things you do at a barber shop',
		'Name 3 things you do at a dentist office',
		'Name 3 things you do at a doctor office',
		'Name 3 things you do at a hospital',
		'Name 3 things you do at a pharmacy',
		'Name 3 things you do at a grocery store',
		'Name 3 things you do at a bank',
		'Name 3 things you do at a post office',
		'Name 3 things you do at a library',
		'Name 3 things you do at a museum',
		'Name 3 things you do at a theater',
		'Name 3 things you do at a stadium',
		'Name 3 things you do at an airport',
		'Name 3 things you do on a plane',
		'Name 3 things you do on a train',
		'Name 3 things you do on a bus',
		'Name 3 things you do on a boat',
		'Name 3 things you do on a bike',
		'Name 3 things you do in a car',
		'Name 3 things you do in a taxi',
		'Name 3 things you do in an Uber',
		'Name 3 things you do in a hotel',
		'Name 3 things you do in a hostel',
		'Name 3 things you do in a campsite',
		'Name 3 things you do in a cabin',
		'Name 3 things you do in a tent',
		'Name 3 things you do in a sleeping bag',
		'Name 3 things you do in a hammock',
		'Name 3 things you do in a bed',
		'Name 3 things you do in a chair',
		'Name 3 things you do at a table',
		'Name 3 things you do on a sofa',
		'Name 3 things you do on a floor',
		'Name 3 things you do on a rug',
		'Name 3 things you do on a stairs',
		'Name 3 things you do on a balcony',
		'Name 3 things you do on a roof',
		'Name 3 things you do on a deck',
		'Name 3 things you do on a patio',
		'Name 3 things you do on a lawn',
		'Name 3 things you do on a street',
		'Name 3 things you do on a sidewalk',
		'Name 3 things you do on a path',
		'Name 3 things you do on a trail',
		'Name 3 things you do on a bridge',
		'Name 3 things you do on a tunnel',
		'Name 3 things you do on a mountain',
		'Name 3 things you do on a hill',
		'Name 3 things you do on a valley',
		'Name 3 things you do on a field',
		'Name 3 things you do on a farm',
		'Name 3 things you do on a ranch',
		'Name 3 things you do on a vineyard',
		'Name 3 things you do on a orchard',
		'Name 3 things you do on a garden',
		'Name 3 things you do on a greenhouse',
		'Name 3 things you do on a shed',
		'Name 3 things you do on a barn',
		'Name 3 things you do on a coop',
		'Name 3 things you do on a kennel',
		'Name 3 things you do on a stable',
		'Name 3 things you do on a paddock',
		'Name 3 things you do on a pasture',
		'Name 3 things you do on a range',
		'Name 3 things you do on a reef',
		'Name 3 things you do on a island',
		'Name 3 things you do on a peninsula',
		'Name 3 things you do on a cape',
		'Name 3 things you do on a bay',
		'Name 3 things you do on a sound',
		'Name 3 things you do on a strait',
		'Name 3 things you do on a channel',
		'Name 3 things you do on a river',
		'Name 3 things you do on a lake',
	],
	hard: [
		'Name 5 Disney princesses',
		'Name 5 Marvel movies',
		'Name 5 Pixar movies',
		'Name 5 Star Wars characters',
		'Name 5 Harry Potter characters',
		'Name 5 Batman villains',
		'Name 5 Spider-Man villains',
		'Name 5 Game of Thrones characters',
		'Name 5 characters from The Simpsons',
		'Name 5 characters from Friends',
		'Name 5 characters from The Office',
		'Name 5 characters from Seinfeld',
		'Name 5 Netflix original shows',
		'Name 5 HBO shows',
		'Name 5 reality TV shows',
		'Name 5 cooking shows',
		'Name 5 game shows',
		'Name 5 soap operas',
		'Name 5 talk show hosts',
		'Name 5 late night hosts',
		'Name 5 female singers',
		'Name 5 male singers',
		'Name 5 rock bands',
		'Name 5 boy bands',
		'Name 5 girl groups',
		'Name 5 rappers',
		'Name 5 country singers',
		'Name 5 jazz musicians',
		'Name 5 classical composers',
		'Name 5 movie directors',
		'Name 5 Oscar winning movies',
		'Name 5 Oscar winning actors',
		'Name 5 Oscar winning actresses',
		'Name 5 Grammy winning artists',
		'Name 5 Emmy winning shows',
		'Name 5 Tony winning musicals',
		'Name 5 Broadway shows',
		'Name 5 Disney songs',
		'Name 5 Christmas carols',
		'Name 5 nursery rhymes',
		'Name 5 fairy tales',
		'Name 5 Greek gods',
		'Name 5 Roman gods',
		'Name 5 Egyptian gods',
		'Name 5 world wonders',
		'Name 5 world capitals',
		'Name 5 world leaders',
		'Name 5 US presidents',
		'Name 5 British monarchs',
		'Name 5 historical figures',
		'Name 5 scientists',
		'Name 5 inventors',
		'Name 5 explorers',
		'Name 5 philosophers',
		'Name 5 authors',
		'Name 5 poets',
		'Name 5 playwrights',
		'Name 5 artists',
		'Name 5 architects',
		'Name 5 fashion designers',
		'Name 5 supermodels',
		'Name 5 social media influencers',
		'Name 5 YouTube stars',
		'Name 5 TikTok trends',
		'Name 5 viral videos',
		'Name 5 memes',
		'Name 5 emojis',
		'Name 5 punctuation marks',
		'Name 5 parts of speech',
		'Name 5 geometric shapes',
		'Name 5 chemical elements',
		'Name 5 noble gases',
		'Name 5 planets in the solar system',
		'Name 5 constellations',
		'Name 5 signs of the zodiac',
		'Name 5 tarot cards',
		'Name 5 playing card suits',
		'Name 5 chess pieces',
		'Name 5 board game pieces',
		'Name 5 Monopoly properties',
		'Name 5 Scrabble tiles',
		'Name 5 video game consoles',
		'Name 5 Nintendo characters',
		'Name 5 Sega characters',
		'Name 5 Pokémon',
		'Name 5 Minecraft blocks',
		'Name 5 Fortnite skins',
		'Name 5 Call of Duty maps',
		'Name 5 sports equipment',
		'Name 5 golf clubs',
		'Name 5 tennis players',
		'Name 5 soccer players',
		'Name 5 basketball players',
		'Name 5 baseball players',
		'Name 5 football players',
		'Name 5 hockey players',
		'Name 5 Olympic host cities',
		'Name 5 Olympic events',
		'Name 5 marathon cities',
		'Name 5 Tour de France winners',
		'Name 5 car models',
		'Name 5 car manufacturers',
		'Name 5 electric cars',
		'Name 5 luxury brands',
		'Name 5 watch brands',
		'Name 5 handbag brands',
		'Name 5 clothing brands',
		'Name 5 shoe brands',
		'Name 5 cosmetic brands',
		'Name 5 perfume brands',
		'Name 5 shampoo brands',
		'Name 5 toothpaste brands',
		'Name 5 cereal brands',
		'Name 5 chocolate bars',
		'Name 5 cookie brands',
		'Name 5 soft drink brands',
		'Name 5 energy drinks',
		'Name 5 beer brands',
		'Name 5 wine varieties',
		'Name 5 cocktail names',
		'Name 5 fast food chains',
		'Name 5 coffee chains',
		'Name 5 restaurant chains',
		'Name 5 supermarket chains',
		'Name 5 department stores',
		'Name 5 online retailers',
		'Name 5 search engines',
		'Name 5 web browsers',
		'Name 5 computer brands',
		'Name 5 phone brands',
		'Name 5 software companies',
		'Name 5 programming languages',
		'Name 5 operating systems',
		'Name 5 file formats',
		'Name 5 fonts',
		'Name 5 colors in the rainbow',
		'Name 5 shades of blue',
		'Name 5 shades of red',
		'Name 5 shades of green',
		'Name 5 primary colors',
		'Name 5 secondary colors',
		'Name 5 metal types',
		'Name 5 gemstone types',
		'Name 5 wood types',
		'Name 5 fabric types',
		'Name 5 flower types',
		'Name 5 tree types',
		'Name 5 dog breeds',
		'Name 5 cat breeds',
		'Name 5 horse breeds',
		'Name 5 bird species',
		'Name 5 fish species',
		'Name 5 insect species',
		'Name 5 reptile species',
		'Name 5 mammal species',
		'Name 5 dinosaur species',
		'Name 5 animal sounds',
		'Name 5 animal habitats',
		'Name 5 desert animals',
		'Name 5 arctic animals',
		'Name 5 rainforest animals',
		'Name 5 savanna animals',
		'Name 5 mountain animals',
		'Name 5 swamp animals',
		'Name 5 farm animals',
		'Name 5 pet names',
		'Name 5 human names',
		'Name 5 baby names',
		'Name 5 surnames',
		'Name 5 nicknames',
		'Name 5 titles',
		'Name 5 honorifics',
		'Name 5 greetings',
		'Name 5 farewells',
		'Name 5 polite phrases',
		'Name 5 exclamation words',
		'Name 5 conjunctions',
		'Name 5 prepositions',
		'Name 5 adjectives',
		'Name 5 adverbs',
		'Name 5 verbs',
		'Name 5 nouns',
		'Name 5 pronouns',
		'Name 5 antonyms',
		'Name 5 synonyms',
		'Name 5 homophones',
		"Name 5 rhymes for 'cat'",
		"Name 5 rhymes for 'love'",
		"Name 5 rhymes for 'blue'",
		"Name 5 rhymes for 'time'",
		"Name 5 rhymes for 'day'",
		"Name 5 rhymes for 'night'",
		"Name 5 rhymes for 'heart'",
		"Name 5 rhymes for 'song'",
		"Name 5 rhymes for 'dance'",
		"Name 5 rhymes for 'fire'",
	],
	hardMature: [
		'Name 5 sex positions',
		'Name 5 safe words',
		'Name 5 illegal drugs',
		'Name 5 slang terms for genitals',
		'Name 5 slang terms for breasts',
		'Name 5 things that make you horny',
		'Name 5 places people have sex',
		'Name 5 things you find in a sex shop',
		'Name 5 types of lingerie',
		'Name 5 kinks or fetishes',
		'Name 5 reasons to swipe left',
		'Name 5 things to do with handcuffs',
		'Name 5 ways to hide a hickey',
		'Name 5 porn categories',
		"Name 5 things you'd find in a dungeon",
		'Name 5 places to hide a dildo',
		'Name 5 adult websites',
		'Name 5 ways to describe an orgasm',
		'Name 5 things you do in a strip club',
		'Name 5 types of lube',
		'Name 5 sexual health terms',
		'Name 5 birth control methods',
		'Name 5 ways to initiate sex',
		'Name 5 things you do during foreplay',
		'Name 5 body parts that are erogenous zones',
		'Name 5 things you say during sex',
		"Name 5 things you shouldn't say during sex",
		'Name 5 things that kill the mood',
		'Name 5 reasons to have a one night stand',
		'Name 5 places for a quickie',
		'Name 5 things to do with whipped cream',
		'Name 5 things to do with ice in bed',
		'Name 5 ways to roleplay',
		'Name 5 costumes for the bedroom',
		'Name 5 toys for couples',
		'Name 5 reasons to visit a swingers club',
		'Name 5 things you find at an orgy',
		'Name 5 rules of a polyamorous relationship',
		'Name 5 things you do in a bath together',
		'Name 5 ways to give a massage',
		'Name 5 things that make someone a bad lover',
		'Name 5 things that make someone a good lover',
		'Name 5 ways to fake it',
		'Name 5 reasons to use a vibrator',
		'Name 5 types of condoms',
		'Name 5 things you find in a bedside drawer',
		"Name 5 places you've been naked in public",
		'Name 5 things that turn you on instantly',
		'Name 5 ways to spice up a relationship',
		'Name 5 things you do after sex',
		'Name 5 awkward things that happen during sex',
		'Name 5 noises people make in bed',
		'Name 5 dirty talk phrases',
		"Name 5 things you'd do for a billion dollars",
		"Name 5 people you'd love to see naked",
		"Name 5 celebrities you'd have a threesome with",
		"Name 5 things you've done while high",
		"Name 5 things you've done while drunk",
		"Name 5 things you've done that were illegal",
		"Name 5 things you've stolen",
		"Name 5 lies you've told a partner",
		"Name 5 secrets you've never told your parents",
		"Name 5 times you've been caught doing something bad",
		"Name 5 things you've done in a car",
		"Name 5 things you've done in a public restroom",
		"Name 5 things you've done in a park",
		"Name 5 things you've done at work you shouldn't have",
		'Name 5 ways to sabotage an ex',
		'Name 5 reasons to stalk an ex on social media',
		"Name 5 things you've said to a bartender to get a free drink",
		'Name 5 ways to get out of paying a bill',
		"Name 5 things you'd find in a drug dealer's house",
		'Name 5 street names for cocaine',
		'Name 5 street names for weed',
		'Name 5 street names for ecstasy',
		'Name 5 ways to take drugs',
		'Name 5 paraphernalia items',
		'Name 5 things you do at a rave',
		'Name 5 things you do at a frat party',
		'Name 5 things you do at a bachelor party',
		'Name 5 things you do at a bachelorette party',
		'Name 5 things you do at a gay bar',
		'Name 5 things you do at a lesbian bar',
		'Name 5 things you do at a leather bar',
		'Name 5 things you do at a fetish club',
		'Name 5 things you do at a goth club',
		'Name 5 things you do at a karaoke bar',
		'Name 5 things you do at a sports bar',
		'Name 5 things you do at a hotel bar',
		'Name 5 things you do at a dive bar',
		'Name 5 things you do at a wine bar',
		'Name 5 things you do at a rooftop bar',
		'Name 5 things you do at a beach bar',
		'Name 5 things you do at a pool party',
		'Name 5 things you do at a garden party',
		'Name 5 things you do at a dinner party',
		'Name 5 things you do at a cocktail party',
		'Name 5 things you do at a holiday party',
		'Name 5 things you do at a birthday party',
		'Name 5 things you do at a wedding reception',
		'Name 5 things you do at a funeral wake',
		'Name 5 things you do at a retirement party',
		'Name 5 things you do at a graduation party',
		'Name 5 things you do at a baby shower',
		'Name 5 things you do at a housewarming party',
		'Name 5 things you do at a surprise party',
		'Name 5 things you do at a themed party',
		'Name 5 things you do at a costume party',
		'Name 5 things you do at a masquerade ball',
		'Name 5 things you do at a black tie event',
		'Name 5 things you do at a red carpet event',
		'Name 5 things you do at a music festival',
		'Name 5 things you do at a film festival',
		'Name 5 things you do at a food festival',
		'Name 5 things you do at a beer festival',
		'Name 5 things you do at a pride parade',
		'Name 5 things you do at a carnival',
		'Name 5 things you do at a circus',
		'Name 5 things you do at a fair',
		'Name 5 things you do at an amusement park',
		'Name 5 things you do at a water park',
		'Name 5 things you do at a zoo',
		'Name 5 things you do at an aquarium',
		'Name 5 things you do at a museum',
		'Name 5 things you do at a gallery',
		'Name 5 things you do at a theater',
		'Name 5 things you do at a cinema',
		'Name 5 things you do at a concert',
		'Name 5 things you do at a gig',
		'Name 5 things you do at a stadium',
		'Name 5 things you do at an arena',
		'Name 5 things you do at a race track',
		'Name 5 things you do at a casino',
		'Name 5 things you do at a bingo hall',
		'Name 5 things you do at a bowling alley',
		'Name 5 things you do at a pool hall',
		'Name 5 things you do at an arcade',
		'Name 5 things you do at a gym',
		'Name 5 things you do at a yoga studio',
		'Name 5 things you do at a dance studio',
		'Name 5 things you do at a spa',
		'Name 5 things you do at a sauna',
		'Name 5 things you do at a steam room',
		'Name 5 things you do at a tanning salon',
		'Name 5 things you do at a hair salon',
		'Name 5 things you do at a nail salon',
		'Name 5 things you do at a barber shop',
		'Name 5 things you do at a tattoo parlor',
		'Name 5 things you do at a piercing studio',
		'Name 5 things you do at a massage parlor',
		"Name 5 things you do at a doctor's office",
		"Name 5 things you do at a dentist's office",
		'Name 5 things you do at a pharmacy',
		'Name 5 things you do at a hospital',
		'Name 5 things you do at a clinic',
		'Name 5 things you do at a laboratory',
		'Name 5 things you do at a morgue',
		'Name 5 things you do at a cemetery',
		'Name 5 things you do at a church',
		'Name 5 things you do at a temple',
		'Name 5 things you do at a mosque',
		'Name 5 things you do at a synagogue',
		'Name 5 things you do at a shrine',
		'Name 5 things you do at a monastery',
		'Name 5 things you do at a convent',
		'Name 5 things you do at a school',
		'Name 5 things you do at a university',
		'Name 5 things you do at a college',
		'Name 5 things you do at a library',
		'Name 5 things you do at a bookstore',
		'Name 5 things you do at a coffee shop',
		'Name 5 things you do at a tea room',
		'Name 5 things you do at a bakery',
		'Name 5 things you do at a deli',
		'Name 5 things you do at a grocery store',
		'Name 5 things you do at a supermarket',
		'Name 5 things you do at a department store',
		'Name 5 things you do at a mall',
		'Name 5 things you do at a market',
		'Name 5 things you do at a street stall',
		'Name 5 things you do at a kiosk',
		'Name 5 things you do at a newsstand',
		'Name 5 things you do at a gas station',
		'Name 5 things you do at a car wash',
		'Name 5 things you do at a garage',
		'Name 5 things you do at a workshop',
		'Name 5 things you do at a factory',
		'Name 5 things you do at a warehouse',
		'Name 5 things you do at a construction site',
		'Name 5 things you do at an office',
		'Name 5 things you do at a studio',
		'Name 5 things you do at a laboratory',
		'Name 5 things you do at a server room',
		'Name 5 things you do at a data center',
		'Name 5 things you do at a radio station',
		'Name 5 things you do at a TV station',
		'Name 5 things you do at a film set',
		'Name 5 things you do at a photo studio',
		'Name 5 things you do at a recording studio',
		'Name 5 things you do at a rehearsal space',
		'Name 5 things you do at a backstage area',
	],
};
